-- MySQL Script generated by MySQL Workbench
-- Tue Jun  3 14:35:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema better_call_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema better_call_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `better_call_test` DEFAULT CHARACTER SET latin1 ;
USE `better_call_test` ;

-- -----------------------------------------------------
-- Table `better_call_test`.`tipos_chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`tipos_chamado` (
  `tch_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tch_descricao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`tch_id`),
  UNIQUE INDEX `tch_id_UNIQUE` (`tch_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`detratores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`detratores` (
  `dtr_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dtr_tipo` INT(10) UNSIGNED NULL DEFAULT NULL,
  `dtr_indicador` INT(10) UNSIGNED NOT NULL DEFAULT '1',
  `dtr_descricao` VARCHAR(100) NOT NULL,
  `dtr_ativo` INT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`dtr_id`),
  UNIQUE INDEX `dtr_id_UNIQUE` (`dtr_id` ASC) VISIBLE,
  INDEX `dtr_tipo_FK_idx` (`dtr_tipo` ASC) VISIBLE,
  CONSTRAINT `dtr_tipo_FK`
    FOREIGN KEY (`dtr_tipo`)
    REFERENCES `better_call_test`.`tipos_chamado` (`tch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`acoes_chamados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`acoes_chamados` (
  `ach_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ach_descricao` TINYTEXT NOT NULL,
  `ach_detrator` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ach_id`),
  UNIQUE INDEX `ach_id_UNIQUE` (`ach_id` ASC) VISIBLE,
  INDEX `ach_detrator_FK_idx` (`ach_detrator` ASC) VISIBLE,
  CONSTRAINT `ach_detrator_FK`
    FOREIGN KEY (`ach_detrator`)
    REFERENCES `better_call_test`.`detratores` (`dtr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 102253
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`chamados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`chamados` (
  `cha_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cha_tipo` INT(10) UNSIGNED NOT NULL,
  `cha_cliente` INT(10) UNSIGNED NOT NULL,
  `cha_produto` INT(10) UNSIGNED NOT NULL,
  `cha_DT` VARCHAR(10) NOT NULL,
  `cha_descricao` TINYTEXT NOT NULL,
  `cha_status` INT(10) UNSIGNED NOT NULL,
  `cha_data_hora_abertura` DATETIME NOT NULL,
  `cha_data_hora_termino` DATETIME NULL DEFAULT NULL,
  `cha_data_hora_atendimento` DATETIME NULL DEFAULT NULL,
  `cha_acao` INT(10) UNSIGNED NULL DEFAULT NULL,
  `cha_operador` VARCHAR(50) NOT NULL,
  `cha_visualizado` TINYINT(1) UNSIGNED ZEROFILL NOT NULL DEFAULT '0',
  `cha_plano` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`cha_id`),
  UNIQUE INDEX `cha_id_UNIQUE` (`cha_id` ASC) VISIBLE,
  INDEX `tipo de chamado_idx` (`cha_tipo` ASC) VISIBLE,
  INDEX `situaÃ§Ã£o do chamado_idx` (`cha_status` ASC) VISIBLE,
  INDEX `aÃ§Ã£o realizada_idx` (`cha_acao` ASC) VISIBLE,
  INDEX `cha_cliente_FK_idx` (`cha_cliente` ASC) VISIBLE,
  INDEX `cha_produto_FK_idx` (`cha_produto` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 102097
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`categorias_colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`categorias_colaboradores` (
  `cac_id` INT(10) UNSIGNED NOT NULL,
  `cac_descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cac_id`),
  UNIQUE INDEX `cac_id_UNIQUE` (`cac_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`colaboradores` (
  `col_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `col_nome` VARCHAR(50) NOT NULL,
  `col_categoria` INT(10) UNSIGNED NOT NULL,
  `col_ativo` INT(1) UNSIGNED ZEROFILL NOT NULL,
  `col_senha` VARCHAR(50) NOT NULL,
  `col_login` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`col_id`),
  UNIQUE INDEX `col_id_UNIQUE` (`col_id` ASC) VISIBLE,
  UNIQUE INDEX `col_login_UNIQUE` (`col_login` ASC) VISIBLE,
  INDEX `Categoria Colaborador_idx` (`col_categoria` ASC) VISIBLE,
  CONSTRAINT `col_categoria_FK`
    FOREIGN KEY (`col_categoria`)
    REFERENCES `better_call_test`.`categorias_colaboradores` (`cac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`ajudantes_chamados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`ajudantes_chamados` (
  `ajc_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ajc_chamado` INT(10) UNSIGNED NOT NULL,
  `ajc_colaborador` INT(10) UNSIGNED NOT NULL,
  `ajc_data_hora` DATETIME NOT NULL,
  PRIMARY KEY (`ajc_id`),
  UNIQUE INDEX `ach_id_UNIQUE` (`ajc_id` ASC) VISIBLE,
  INDEX `Id Chamado_idx` (`ajc_chamado` ASC) VISIBLE,
  INDEX `Id Colaborador_idx` (`ajc_colaborador` ASC) VISIBLE,
  CONSTRAINT `ajc_chamado_FK`
    FOREIGN KEY (`ajc_chamado`)
    REFERENCES `better_call_test`.`chamados` (`cha_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ajc_colaborador_FK`
    FOREIGN KEY (`ajc_colaborador`)
    REFERENCES `better_call_test`.`colaboradores` (`col_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 337
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`atendimentos_chamados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`atendimentos_chamados` (
  `atc_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `atc_chamado` INT(10) UNSIGNED NOT NULL,
  `atc_colaborador` INT(10) UNSIGNED NOT NULL,
  `atc_data_hora_inicio` DATETIME NOT NULL,
  `atc_data_hora_termino` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`atc_id`),
  UNIQUE INDEX `ach_UNIQUE` (`atc_id` ASC) VISIBLE,
  INDEX `ach_chamado_FK_idx` (`atc_chamado` ASC) VISIBLE,
  INDEX `ach_colaborador_FK_idx` (`atc_colaborador` ASC) VISIBLE,
  CONSTRAINT `atc_colaborador_FK`
    FOREIGN KEY (`atc_colaborador`)
    REFERENCES `better_call_test`.`colaboradores` (`col_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 117748
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`clientes` (
  `cli_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cli_nome` VARCHAR(50) NOT NULL,
  `cli_responsavel` INT(10) UNSIGNED NULL DEFAULT NULL,
  `cli_ativo` INT(10) UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`cli_id`),
  UNIQUE INDEX `cli_id_UNIQUE` (`cli_id` ASC) VISIBLE,
  INDEX `cli_responsavel_FK_idx` (`cli_responsavel` ASC) VISIBLE,
  CONSTRAINT `cli_responsavel_FK`
    FOREIGN KEY (`cli_responsavel`)
    REFERENCES `better_call_test`.`colaboradores` (`col_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 336
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`computadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`computadores` (
  `cmp_id` INT(10) NOT NULL AUTO_INCREMENT,
  `cmp_identificacao` VARCHAR(45) NULL DEFAULT NULL,
  `cmp_proprietario` VARCHAR(45) NULL DEFAULT NULL,
  `cmp_etapa_teste` VARCHAR(45) NULL DEFAULT NULL,
  `cmp_programas_instalados` TEXT NULL DEFAULT NULL,
  `cmp_sis_operacional` VARCHAR(45) NULL DEFAULT NULL,
  `cmp_localizacao` VARCHAR(45) NULL DEFAULT NULL,
  `cmp_observacao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`cmp_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `better_call_test`.`formularios_manutencao_preventiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`formularios_manutencao_preventiva` (
  `fmp_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fmp_descricao` VARCHAR(100) NOT NULL,
  `fmp_data_ultima_modificacao` DATETIME NULL DEFAULT NULL,
  `fmp_modificador` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`fmp_id`),
  UNIQUE INDEX `fmp_id_UNIQUE` (`fmp_id` ASC) VISIBLE,
  INDEX `fmp_modificador_FK_idx` (`fmp_modificador` ASC) VISIBLE,
  CONSTRAINT `fmp_modificador_FK`
    FOREIGN KEY (`fmp_modificador`)
    REFERENCES `better_call_test`.`colaboradores` (`col_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`dispositivo_info_manutencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`dispositivo_info_manutencao` (
  `dim_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dim_tipo_intervalo` ENUM('DIA', 'PLACA') NULL DEFAULT NULL,
  `dim_intervalo_dias` INT(10) NOT NULL DEFAULT '0',
  `dim_intervalo_placas` INT(10) NOT NULL DEFAULT '0',
  `dim_placas_executadas` INT(10) NOT NULL DEFAULT '0',
  `dim_formulario_manutencao` INT(10) UNSIGNED NULL DEFAULT NULL,
  `dim_data_ultima_manutencao` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`dim_id`),
  UNIQUE INDEX `dim_id_UNIQUE` (`dim_id` ASC) VISIBLE,
  INDEX `dim_formulario_manutencao_FK_idx` (`dim_formulario_manutencao` ASC) VISIBLE,
  CONSTRAINT `dim_formulario_manutencao_FK`
    FOREIGN KEY (`dim_formulario_manutencao`)
    REFERENCES `better_call_test`.`formularios_manutencao_preventiva` (`fmp_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 606
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`notas_fiscais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`notas_fiscais` (
  `nof_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nof_numero` VARCHAR(10) NOT NULL,
  `nof_cliente` INT(10) UNSIGNED NOT NULL,
  `nof_doc_sap` VARCHAR(10) NOT NULL,
  `nof_data_hora_cadastro` DATETIME NOT NULL,
  `nof_com_retorno` INT(1) UNSIGNED NOT NULL,
  `nof_data_retorno` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`nof_id`),
  UNIQUE INDEX `nof_id_UNIQUE` (`nof_id` ASC) VISIBLE,
  INDEX `nof_cliente_FK_idx` (`nof_cliente` ASC) VISIBLE,
  CONSTRAINT `nof_cliente_FK`
    FOREIGN KEY (`nof_cliente`)
    REFERENCES `better_call_test`.`clientes` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 360
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`entrada_saida_equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`entrada_saida_equipamento` (
  `ese_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ese_nota_fiscal_entrada` INT(10) UNSIGNED NOT NULL,
  `ese_numero_nota_fiscal_saida` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ese_dispositivo` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`ese_id`),
  UNIQUE INDEX `ese_id_UNIQUE` (`ese_id` ASC) VISIBLE,
  INDEX `ese_nota_fiscal_entrada_FK_idx` (`ese_nota_fiscal_entrada` ASC) VISIBLE,
  INDEX `ese_dispositivo_FK_idx` (`ese_dispositivo` ASC) VISIBLE,
  CONSTRAINT `ese_dispositivo_FK`
    FOREIGN KEY (`ese_dispositivo`)
    REFERENCES `better_call_test`.`dispositivos` (`dis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ese_nota_fiscal_entrada_FK`
    FOREIGN KEY (`ese_nota_fiscal_entrada`)
    REFERENCES `better_call_test`.`notas_fiscais` (`nof_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 722
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`status_dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`status_dispositivo` (
  `sdi_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sdi_descricao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`sdi_id`),
  UNIQUE INDEX `idstatus_dispositivo_UNIQUE` (`sdi_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`dispositivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`dispositivos` (
  `dis_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dis_descricao` VARCHAR(60) CHARACTER SET 'utf8' NOT NULL,
  `dis_cliente` INT(10) UNSIGNED NULL DEFAULT NULL,
  `dis_nota_fiscal_atual` INT(10) UNSIGNED NULL DEFAULT NULL,
  `dis_com_manutencao` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `dis_info_manutencao` INT(10) UNSIGNED NULL DEFAULT NULL,
  `dis_data_cadastro` DATETIME NOT NULL,
  `dis_codigo_sap` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dis_com_imagem` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `dis_status` INT(10) UNSIGNED NOT NULL DEFAULT '1',
  `dis_observacao` TINYTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dis_ciclos_de_vida` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `dis_ciclos_executados` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `dis_doc_enviado` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `dis_extensao_imagem` VARCHAR(5) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dis_posicao_estoque` VARCHAR(5) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dis_local` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`dis_id`),
  UNIQUE INDEX `dis_id_UNIQUE` (`dis_id` ASC) VISIBLE,
  INDEX `dis_cliente_FK_idx` (`dis_cliente` ASC) VISIBLE,
  INDEX `dis_nota_fiscal_atual_FK_idx` (`dis_nota_fiscal_atual` ASC) VISIBLE,
  INDEX `dis_info_manutencao_FK_idx` (`dis_info_manutencao` ASC) VISIBLE,
  INDEX `dis_status_FK_idx` (`dis_status` ASC) VISIBLE,
  CONSTRAINT `dis_cliente_FK`
    FOREIGN KEY (`dis_cliente`)
    REFERENCES `better_call_test`.`clientes` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dis_info_manutencao_FK`
    FOREIGN KEY (`dis_info_manutencao`)
    REFERENCES `better_call_test`.`dispositivo_info_manutencao` (`dim_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dis_nota_fiscal_atual_FK`
    FOREIGN KEY (`dis_nota_fiscal_atual`)
    REFERENCES `better_call_test`.`entrada_saida_equipamento` (`ese_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dis_status_FK`
    FOREIGN KEY (`dis_status`)
    REFERENCES `better_call_test`.`status_dispositivo` (`sdi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 864
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `better_call_test`.`funcoes_equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`funcoes_equipamento` (
  `feq_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `feq_descricao` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`feq_id`),
  UNIQUE INDEX `feq_UNIQUE` (`feq_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`hardware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`hardware` (
  `hrd_id` INT(10) NOT NULL AUTO_INCREMENT,
  `hrd_nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`hrd_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `better_call_test`.`indicadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`indicadores` (
  `ind_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ind_data` DATE NOT NULL,
  `ind_minutos_diario` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ind_atendimento_diario` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ind_atraso_diario` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ind_minutos_semanal` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ind_atendimento_semanal` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ind_atraso_semanal` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ind_minutos_mensal` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ind_atendimento_mensal` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ind_atraso_mensal` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`ind_id`),
  UNIQUE INDEX `ind_id_UNIQUE` (`ind_id` ASC) VISIBLE,
  UNIQUE INDEX `ind_data_UNIQUE` (`ind_data` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1703
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`itens_formulario_manutencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`itens_formulario_manutencao` (
  `ifm_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ifm_formulario` INT(10) UNSIGNED NOT NULL,
  `ifm_descricao` TINYTEXT NOT NULL,
  `ifm_posicao` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ifm_id`),
  UNIQUE INDEX `ifm_id_UNIQUE` (`ifm_id` ASC) VISIBLE,
  INDEX `ifm_formulario_FK` (`ifm_formulario` ASC) VISIBLE,
  CONSTRAINT `ifm_formulario_FK`
    FOREIGN KEY (`ifm_formulario`)
    REFERENCES `better_call_test`.`formularios_manutencao_preventiva` (`fmp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`status_manutencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`status_manutencao` (
  `sma_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sma_descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sma_id`),
  UNIQUE INDEX `sma_id_UNIQUE` (`sma_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`log_manutencao_dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`log_manutencao_dispositivo` (
  `lmd_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `lmd_dispositivo` INT(10) UNSIGNED NOT NULL,
  `lmd_data_hora_inicio` DATETIME NOT NULL,
  `lmd_data_hora_fim` DATETIME NULL DEFAULT NULL,
  `lmd_tipo_manutencao` ENUM('PREVENTIVA', 'CORRETIVA') NOT NULL,
  `lmd_ciclos_totais_executados` INT(10) UNSIGNED NOT NULL,
  `lmd_data_hora_ultima_manutencao` DATETIME NULL DEFAULT NULL,
  `lmd_tipo_intervalo_manutencao` ENUM('DIA', 'PLACA') NOT NULL,
  `lmd_intervalo_dias` INT(10) UNSIGNED NOT NULL,
  `lmd_intervalo_placas` INT(10) UNSIGNED NOT NULL,
  `lmd_placas_executadas` INT(10) UNSIGNED NOT NULL,
  `lmd_observacao` TEXT NULL DEFAULT NULL,
  `lmd_colaborador` INT(10) UNSIGNED NOT NULL,
  `lmd_status` INT(10) UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`lmd_id`),
  UNIQUE INDEX `lmd_id_UNIQUE` (`lmd_id` ASC) VISIBLE,
  INDEX `lmd_dispositivo_FK_idx` (`lmd_dispositivo` ASC) VISIBLE,
  INDEX `lmd_colaborador_FK_idx` (`lmd_colaborador` ASC) VISIBLE,
  INDEX `lmd_status_FK_idx` (`lmd_status` ASC) VISIBLE,
  CONSTRAINT `lmd_colaborador_FK`
    FOREIGN KEY (`lmd_colaborador`)
    REFERENCES `better_call_test`.`colaboradores` (`col_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lmd_dispositivo_FK`
    FOREIGN KEY (`lmd_dispositivo`)
    REFERENCES `better_call_test`.`dispositivos` (`dis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lmd_status_FK`
    FOREIGN KEY (`lmd_status`)
    REFERENCES `better_call_test`.`status_manutencao` (`sma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2189
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`planos_de_producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`planos_de_producao` (
  `pdp_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pdp_data` DATE NOT NULL,
  `pdp_total_horas` INT(10) UNSIGNED NOT NULL,
  `pdp_total_producao` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`pdp_id`),
  UNIQUE INDEX `pdp_id_UNIQUE` (`pdp_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1188
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`produtos` (
  `pro_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pro_nome` VARCHAR(50) NOT NULL,
  `pro_cliente` INT(10) UNSIGNED NOT NULL,
  `pro_ativo` INT(1) UNSIGNED NOT NULL DEFAULT '1',
  `pro_com_teste` INT(1) UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`pro_id`),
  UNIQUE INDEX `pro_id_UNIQUE` (`pro_id` ASC) VISIBLE,
  INDEX `pro_cliente_FK_idx` (`pro_cliente` ASC) VISIBLE,
  CONSTRAINT `pro_cliente_FK`
    FOREIGN KEY (`pro_cliente`)
    REFERENCES `better_call_test`.`clientes` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12552
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`ordens_de_producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`ordens_de_producao` (
  `odp_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `odp_plano_de_producao` INT(10) UNSIGNED NOT NULL,
  `odp_cliente` INT(10) UNSIGNED NOT NULL,
  `odp_produto` INT(10) UNSIGNED NOT NULL,
  `odp_quantidade` INT(10) UNSIGNED NOT NULL,
  `odp_hora_inicio` TIME NOT NULL,
  `odp_horas_producao` INT(11) NOT NULL,
  PRIMARY KEY (`odp_id`),
  UNIQUE INDEX `odp_id_UNIQUE` (`odp_id` ASC) VISIBLE,
  INDEX `odp_plano_de_producao_FK_idx` (`odp_plano_de_producao` ASC) VISIBLE,
  INDEX `odp_cliente_FK_idx` (`odp_cliente` ASC) VISIBLE,
  INDEX `odp_produto_FK_idx` (`odp_produto` ASC) VISIBLE,
  CONSTRAINT `odp_cliente_FK`
    FOREIGN KEY (`odp_cliente`)
    REFERENCES `better_call_test`.`clientes` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `odp_plano_de_producao_FK`
    FOREIGN KEY (`odp_plano_de_producao`)
    REFERENCES `better_call_test`.`planos_de_producao` (`pdp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `odp_produto_FK`
    FOREIGN KEY (`odp_produto`)
    REFERENCES `better_call_test`.`produtos` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 40625
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`posicoes_dispositivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`posicoes_dispositivos` (
  `pdi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pdi_tipo` VARCHAR(45) NULL DEFAULT NULL,
  `pdi_posicao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pdi_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `better_call_test`.`programas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`programas` (
  `pgr_id` INT(10) NOT NULL AUTO_INCREMENT,
  `pgr_nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pgr_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 121
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `better_call_test`.`resposta_item_formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`resposta_item_formulario` (
  `rif_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `rif_item` INT(10) UNSIGNED NOT NULL,
  `rif_log_manutencao` INT(10) UNSIGNED NOT NULL,
  `rif_ok` BINARY(1) NOT NULL,
  `rif_observacao` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`rif_id`),
  UNIQUE INDEX `rif_id_UNIQUE` (`rif_id` ASC) VISIBLE,
  INDEX `rif_item_FK_idx` (`rif_item` ASC) VISIBLE,
  INDEX `rif_log_manutencao_FK_idx` (`rif_log_manutencao` ASC) VISIBLE,
  CONSTRAINT `rif_item_FK`
    FOREIGN KEY (`rif_item`)
    REFERENCES `better_call_test`.`itens_formulario_manutencao` (`ifm_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `rif_log_manutencao_FK`
    FOREIGN KEY (`rif_log_manutencao`)
    REFERENCES `better_call_test`.`log_manutencao_dispositivo` (`lmd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10159
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`status_chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`status_chamado` (
  `stc_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `stc_descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`stc_id`),
  UNIQUE INDEX `stc_id_UNIQUE` (`stc_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `better_call_test`.`vinculacao_computadores_hardware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`vinculacao_computadores_hardware` (
  `vch_cmp_id` INT(10) NOT NULL,
  `vch_hrd_id` INT(10) NOT NULL,
  `vch_id` INT(10) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`vch_id`, `vch_cmp_id`, `vch_hrd_id`),
  INDEX `fk_computadores_has_hardware_hardware1_idx` (`vch_hrd_id` ASC) VISIBLE,
  INDEX `fk_computadores_has_hardware_computadores1_idx` (`vch_cmp_id` ASC) VISIBLE,
  CONSTRAINT `fk_computadores_has_hardware_computadores1`
    FOREIGN KEY (`vch_cmp_id`)
    REFERENCES `better_call_test`.`computadores` (`cmp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_computadores_has_hardware_hardware1`
    FOREIGN KEY (`vch_hrd_id`)
    REFERENCES `better_call_test`.`hardware` (`hrd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 190
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `better_call_test`.`vinculacao_computadores_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`vinculacao_computadores_produtos` (
  `vcp_produtos_pro_id` INT(10) UNSIGNED NOT NULL,
  `vcp_computadores_cmp_id` INT(10) NOT NULL,
  `vcp_etapa_teste` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`vcp_produtos_pro_id`, `vcp_computadores_cmp_id`),
  INDEX `fk_produtos_has_computadores_computadores1_idx` (`vcp_computadores_cmp_id` ASC) VISIBLE,
  INDEX `fk_produtos_has_computadores_produtos1_idx` (`vcp_produtos_pro_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_has_computadores_computadores1`
    FOREIGN KEY (`vcp_computadores_cmp_id`)
    REFERENCES `better_call_test`.`computadores` (`cmp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_computadores_produtos1`
    FOREIGN KEY (`vcp_produtos_pro_id`)
    REFERENCES `better_call_test`.`produtos` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `better_call_test`.`vinculacao_computadores_programas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`vinculacao_computadores_programas` (
  `vpc_id` INT(10) NOT NULL AUTO_INCREMENT,
  `vpc_computadores_cmp_id` INT(10) NOT NULL,
  `vpc_programas_pgr_id` INT(10) NOT NULL,
  PRIMARY KEY (`vpc_id`, `vpc_computadores_cmp_id`, `vpc_programas_pgr_id`),
  INDEX `fk_computadores_has_programas_programas1_idx` (`vpc_programas_pgr_id` ASC) VISIBLE,
  INDEX `fk_computadores_has_programas_computadores1_idx` (`vpc_computadores_cmp_id` ASC) VISIBLE,
  CONSTRAINT `fk_computadores_has_programas_computadores1`
    FOREIGN KEY (`vpc_computadores_cmp_id`)
    REFERENCES `better_call_test`.`computadores` (`cmp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_computadores_has_programas_programas1`
    FOREIGN KEY (`vpc_programas_pgr_id`)
    REFERENCES `better_call_test`.`programas` (`pgr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 378
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `better_call_test`.`vinculacao_dispositivo_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `better_call_test`.`vinculacao_dispositivo_produto` (
  `vdp_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `vdp_dispositivo` INT(10) UNSIGNED NOT NULL,
  `vdp_produto` INT(10) UNSIGNED NOT NULL,
  `vdp_funcao_dispositivo` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`vdp_id`),
  UNIQUE INDEX `vdp_id_UNIQUE` (`vdp_id` ASC) VISIBLE,
  INDEX `vdp_dispositivo_FK_idx` (`vdp_dispositivo` ASC) VISIBLE,
  INDEX `vdp_produto_FK_idx` (`vdp_produto` ASC) VISIBLE,
  INDEX `vdp_funcao_dispositivo_FK_idx` (`vdp_funcao_dispositivo` ASC) VISIBLE,
  CONSTRAINT `vdp_dispositivo_FK`
    FOREIGN KEY (`vdp_dispositivo`)
    REFERENCES `better_call_test`.`dispositivos` (`dis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vdp_funcao_dispositivo_FK`
    FOREIGN KEY (`vdp_funcao_dispositivo`)
    REFERENCES `better_call_test`.`funcoes_equipamento` (`feq_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vdp_produto_FK`
    FOREIGN KEY (`vdp_produto`)
    REFERENCES `better_call_test`.`produtos` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2503
DEFAULT CHARACTER SET = utf8;

USE `better_call_test`;

DELIMITER $$
USE `better_call_test`$$
/*!50003 CREATE*/ /*!50017 DEFINER=`bct`@`%`*/ /*!50003 TRIGGER atualizador_manutencao_preventiva
AFTER INSERT ON ordens_de_producao
FOR EACH ROW
BEGIN
	DECLARE done INT DEFAULT FALSE;
	DECLARE device_function integer;
	DECLARE device_function_counter integer;
	DECLARE devices_cursor CURSOR FOR 
		SELECT 
			vdp_funcao_dispositivo, 
			COUNT(vdp_funcao_dispositivo) 
		FROM 
			vinculacao_dispositivo_produto 
			LEFT JOIN dispositivos ON vdp_dispositivo = dis_id 
			LEFT JOIN dispositivo_info_manutencao ON dis_info_manutencao = dim_id 
		WHERE 
			dis_status <> 3 
			AND vdp_produto = NEW.odp_produto
		GROUP BY 
			vdp_funcao_dispositivo;
			
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;	
	
			
	OPEN devices_cursor;
	
	up_loop: LOOP
		FETCH devices_cursor INTO device_function, device_function_counter;
		IF done THEN
			LEAVE up_loop;
		END IF;
		
		UPDATE vinculacao_dispositivo_produto 
			LEFT JOIN dispositivos ON vdp_dispositivo = dis_id 
			LEFT JOIN dispositivo_info_manutencao ON dis_info_manutencao = dim_id 
		SET	
			dim_placas_executadas = dim_placas_executadas + (NEW.odp_quantidade/device_function_counter)
		WHERE
			vdp_funcao_dispositivo = device_function
			AND dis_status <> 3
			AND vdp_produto = NEW.odp_produto
			AND dim_tipo_intervalo = "PLACA";
			
		UPDATE vinculacao_dispositivo_produto 
			LEFT JOIN dispositivos ON vdp_dispositivo = dis_id 
			LEFT JOIN dispositivo_info_manutencao ON dis_info_manutencao = dim_id 
		SET	
			dis_ciclos_executados = dis_ciclos_executados + (NEW.odp_quantidade/device_function_counter)
		WHERE
			vdp_funcao_dispositivo = device_function
			AND dis_status <> 3
			AND vdp_produto = NEW.odp_produto;
			
	END LOOP;
		
	CLOSE devices_cursor;	

END */$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
